### ISSUE TITLE
openai.OpenAIError: The api_key client option

### ISSUE THREAD

**Issue by merolaika** [MainAIdk/AI-short-generator#1]
Hello there,

i get this error;

`
(myvenv) (base) C:\Python\AI-short-generator>python main.py source.txt
Traceback (most recent call last):
  File "C:\Python\AI-short-generator\main.py", line 13, in <module>
    import images
  File "C:\Python\AI-short-generator\images.py", line 7, in <module>
    client = OpenAI()
             ^^^^^^^^
  File "C:\Python\AI-short-generator\myvenv\Lib\site-packages\openai\_client.py", line 98, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
`

**Comment by matztheone** [comment]
Hello @merolaika 

It seems like the API key for OpenAI is not being set correctly. 
Did you rename the ".env copy" to ".env" and set up your keys in there?

Otherwise you could try setting it manually for the session using this command `set OPENAI_API_KEY=YOUR_API_KEY`

Let me know if it works or if you need any help

**Comment by merolaika** [comment]
Hello again,

Yep i change "env copy" to "env"
I created a new api in case there is a problem in the api, I added it to the env file, but it gives the same error again. I also used the set OPENAI_API_KEY=**** command and I encountered the same problem again. I would like your help. Thanks


My Python version:
Python 3.11.5

**Comment by matztheone** [comment]
Hmmm

That's strange and you installed the used the `pip install -r requirements.txt` ?

I'm asking because it should install the python library called python-dotenv which is responsible for loading the .env file in main.py


Could you please try using this command to see all environment variables set in your current seesion?  `Get-ChildItem Env:` look for the OPENAI_API_KEY

If you cannot find it there then please set it manually but with this command `$env:OPENAI_API_KEY=your_api_key`

Let me know if it works or you need any more help

**Comment by merolaika** [comment]
Hello,  $env:OPENAI_API_KEY=your_api_key its working. Thanks so much
